### ISSUE TITLE
Restart timeout on runit is too low

### ISSUE THREAD

**Issue by elliott-davis** [lusis/chef-logstash#390]
Runit's default timeout is 7 seconds.  This is way to low for logstash to restart successfully.  In my testing 240 seconds was an arbitrarily high enough timeout.

**Comment by cmjosh** [comment]
I ran into this same issue on an instance today (oddly just a few hours before this issue was closed - go figure).  It doesn't seem to be consistent.  The next instance I tried it was fine and I didn't see the timeout.  For reference, here's a quick change I started to add a timeout attribute: https://github.com/creativemarket/chef-logstash/compare/runit_timeout?expand=1 .  Unfortunately, still untested since I couldn't reproduce it on the second instance.
